name: Update MediaKlikk Playlist

on:
  schedule:
    - cron: "*/59 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3️⃣ Install dependencies
      - run: pip install requests

      # 4️⃣ Run MediaKlikk script (in root!)
      - run: python3 Update_Mediaklikk_streams.py

      # 5️⃣ Commit en push playlist
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlists/TCL.m3u
          git commit -m "Update MediaKlikk streams" || exit 0
          git push
