name: update-jwplayer

on:
  schedule:
    - cron: '0 */6 * * *'   # elke 6 uur
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run scraper
      run: |
        python Update_JWPlayer_streams.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add TCL.m3u

        git diff --cached --quiet || git commit -m "🔄 JWPlayer streams updated"

        git push
