name: Update JWPlayer Streams

on:
  schedule:
    - cron: '0 * * * *'  # Elk uur
  workflow_dispatch:

jobs:
  update_jwplayer:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run JWPlayer scraper
        run: python Update_JWPlayer_streams.py

      - name: Commit updated TCL.m3u
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add TCL.m3u
          git commit -m "Update JWPlayer streams" || echo "No changes to commit"
          git push
