name: JWPlayer Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/59 * * * *"
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium requests webdriver-manager

      - name: Run JWPlayer Selenium scraper
        run: python Update_JWPlayer_streams.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add TCL.m3u

          git commit -m "📡 JWPlayer streams refreshed" || echo "No changes"

          git pull origin master --rebase
          git push

