name: Update Aftermind Streams

on:
  schedule:
    # Elke uur op minuut 0
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run Aftermind scraper
        run: python Update_Aftermind_stream.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add TCL.m3u
          git commit -m "Update Aftermind streams" || echo "No changes"
          git push
