name: Update Cycling Playlist

on:
  schedule:
    - cron: "0 21 * * *"   # 23:00 België
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run scraper
        run: python tiz_selenium_m3u.py

      - name: Commit changes
        run: |
          git config --global user.name "playlist-bot"
          git config --global user.email "playlist-bot@users.noreply.github.com"
          git add Cycling.m3u
          git commit -m "Auto update Cycling.m3u" || echo "No changes"
          git push
